#!/bin/bash

# Deploy release/assets on GitHub
# Assumes Travis CI is the build system
# For Linux and OSX

OS=$TRAVIS_OS_NAME
CURRENT_BRANCH=$TRAVIS_BRANCH
REPOURL="https://api.github.com/repos/${TRAVIS_REPO_SLUG}"
DEVELOPMENT_BRANCH="develop"
JQRELEASEURL="https://github.com/stedolan/jq/releases/download/jq-1.6"
RELEASE_NAME="UnnamedRelease"
RELEASE_BODY=""
RELEASE_BODY_FILE=""
RELEASE_BODY_FILE_WARN="false"
RELEASE_PRE="false"
ARTIFACTS=""
NARTIFACTS=0

# Parse options
while getopts ":n:b:d:f:p" opt
do
	case "${opt}" in
		b)
			RELEASE_BODY=${OPTARG}
			echo "Release body set to '${RELEASE_BODY}'"
			;;
		d)
			DEVELOPMENT_BRANCH=${OPTARG}
			echo "Development branch which spawns continuous releases set to '${DEVELOPMENT_BRANCH=}'"
			;;
		f)
			RELEASE_BODY_FILE=${OPTARG}
			echo "Release body will be set from markdown file '${RELEASE_BODY_FILE}'"
			;;
		w)
			RELEASE_BODY_FILE_WARN="true"
			echo "A non-existent release body file will not cause an error."
			;;
		n)
			RELEASE_NAME=${OPTARG}
			echo "Release name set to '${RELEASE_NAME}'"
			;;
		p)
			RELEASE_PRE="true"
			echo "Release will be marked as a pre-release."
			;;
		*)
			echo "$0 [-n release_name] [-b release_body] [-p] artifacts ..."
			;;
	esac
done

# Enable erroring
set -e

# Disable command expansion so we don't leak secrets
set +x

# Assemble array of artifacts to upload to release
shift $(expr $OPTIND - 1)
while test $# -gt 0
do
	if [ ! -f $1 ]
	then
		echo "Error: No such artifact '$1' exists."
		exit 1
	fi
	ARTIFACTS[NARTIFACTS]=$1
	let NARTIFACTS=NARTIFACTS+1
	shift
done

# Load and process release body file if required
if [ "x$RELEASE_BODY_FILE" != "x" ]
then
	if [ -e $RELEASE_BODY_FILE ]
	then
		# Read in the file, preserving line-feeds
		RELEASE_BODY=$(<$RELEASE_BODY_FILE)

		# Convert LF to <br/>
		RELEASE_BODY=${RELEASE_BODY//$'\n'/<br\/>}
	elif [ "$RELEASE_BODY_FILE_WARN" = "true" ]
	then
		echo "Warning: Release body file $RELEASE_BODY_FILE specified, but it does not exist."
	else
		echo "Error: Release body file $RELEASE_BODY_FILE does not exist."
		exit 1
	fi
fi

# Retrieve jq to do the JSON parsing
if [ "${OS}" = "osx" ]
then
	wget -q ${JQRELEASEURL}/jq-osx-amd64 -O jq
elif [ "${OS}" = "linux" ]
then
	wget -q ${JQRELEASEURL}/jq-linux64 -O jq
else
	echo "Unrecognised OS '${OS}'."
	exit 1
fi

# Make the jq binary executable
chmod u+x ./jq

# Set a suitable tag if we are deploying a continuous release
if [ "${CURRENT_BRANCH}" = "${DEVELOPMENT_BRANCH}" ]
then
	export TRAVIS_TAG=continuous/$(git log --format=%h -1)

	# Set appropriate name/body
	RELEASE_NAME="Continuous build"

	# If a body file was given, append the data to our standard header
	BODY="Continuous build ${TRAVIS_COMMIT} (${TRAVIS_JOB_WEB_URL})"
	if [ "x$RELEASE_BODY_FILE" != "x" ] && [ -e $RELEASE_BODY_FILE ]
	then
		BODY="${BODY}<br/>${RELEASE_BODY}"
	fi
	RELEASE_BODY=$BODY

	echo "Note: release name and body have been set appropriately for a continuous build."
fi

# Check tag
if [ "x$TRAVIS_TAG" = "x" ]
then
	echo "Error: No tag for current release - check your setup (did you push a release without --tags?)."
	exit 1
fi
echo "Tag for release is: $TRAVIS_TAG"

# Get available releases information
RELEASES=$(curl -XGET --header "Authorization: token ${GITHUB_TOKEN}" ${REPOURL}/releases)

# Does our tag already have a release?
echo "Checking for presence of current release..."
FILTER=".[] | select(.tag_name | match(\"$TRAVIS_TAG\"))"
CURRENT_RELEASEINFO=$(echo $RELEASES | ./jq "$FILTER")
CURRENT_URL=$(echo $CURRENT_RELEASEINFO | ./jq -r '. | .url')
if [ "x$CURRENT_URL" = "x" ]
then
	echo " -- No release with tag $TRAVIS_TAG currently exists."
	echo "    A new one will be created."
	if [ "${CURRENT_BRANCH}" = "${DEVELOPMENT_BRANCH}" ]
	then
		echo "    The current source will be tagged as a continuous build..."

		# Set GitHub username and email
		git config --local user.name "trisyoungs"
		git config --local user.email "tristan.youngs@stfc.ac.uk"

		git tag $TRAVIS_TAG
	fi
else
	echo " -- Found existing release with tag $TRAVIS_TAG"
	echo "    url: $CURRENT_URL"
fi

# Prune old continuous releases if we are building from the specified development branch
echo "Current branch: '${CURRENT_BRANCH}'"
if [ "${CURRENT_BRANCH}" = "${DEVELOPMENT_BRANCH}" ]
then
	echo "Pruning old continuous releases..."

	# Filter release information with jq to get the continuous build urls and tags to delete
	URLS=$(echo $RELEASES | ./jq -r '.[] | select(.tag_name | match("continuous/.*")) | .url')
	TAGS=$(echo $RELEASES | ./jq -r '.[] | select(.tag_name | match("continuous/.*")) | .tag_name')

	# Delete old continuous releases (but not the current one if it exists)
	echo "  - Found continuous release url(s): "$URLS
	for url in $URLS
	do
		if [ "$url" = "$CURRENT_URL" ]
		then
			echo " -- Existing continuous release at $url will not be deleted as it is the current release."
			continue
		fi
		echo "  ! Deleting continuous release at $url..."
		curl -XDELETE --header "Authorization: token ${GITHUB_TOKEN}" $url
	done

	# Delete tags (but not the current one if it exists)
	echo "  - Found tags: "$TAGS
	for tag in $TAGS
	do
		if [ "$tag" = "$TRAVIS_TAG" ]
		then
			echo " -- Existing continuous release reference $tag will not be deleted as it is the current release."
			continue
		fi
		echo "  ! Deleting reference $tag..."
		curl -XDELETE --header "Authorization: token ${GITHUB_TOKEN}" ${REPOURL}/git/refs/tags/${tag}
	done
fi

# If we don't already have info for our release, create one now
if [ "x$CURRENT_URL" = "x" ]
then
	# Construct release information
	RELEASE_DATA='{ "tag_name": "'$TRAVIS_TAG'"'
	RELEASE_DATA=${RELEASE_DATA}', "target_commitish": "'$TRAVIS_COMMIT'"'
	RELEASE_DATA=${RELEASE_DATA}', "name": "'$RELEASE_NAME'"'
	RELEASE_DATA=${RELEASE_DATA}', "body": "'$RELEASE_BODY'"'
	RELEASE_DATA=${RELEASE_DATA}', "draft": false'
	RELEASE_DATA=${RELEASE_DATA}', "prerelease": '$RELEASE_PRE
	RELEASE_DATA=${RELEASE_DATA}" }"
	echo $RELEASE_DATA

	# Create release
	CURRENT_RELEASEINFO=$(curl --header "Authorization: token ${GITHUB_TOKEN}" --data "$RELEASE_DATA" ${REPOURL}/releases)

	# Extract url
	CURRENT_URL=$(echo $CURRENT_RELEASEINFO | ./jq -r '. | .url')
fi

# Extract upload path for assets
# -- Need to strip trailing {?name,label} part from the returned url
UPLOAD_URL=$(echo $CURRENT_RELEASEINFO | ./jq -r '. | .upload_url' | cut -d '{' -f 1)
if [ "x$UPLOAD_URL" = "x" ]
then
	echo "Error: Failed to determine upload url for release."
	exit 1
fi
echo "Upload url is: $UPLOAD_URL"

# Upload specified assets
echo "Uploading assets to release..."

for file in ${ARTIFACTS[@]}
do
	# Get the basename of the file so we call it the correct name
	BASENAME=$(basename "${file}")
	echo "... $file (basename=$BASENAME)"

	ARTIFACT_DATA=$(curl --header "Authorization: token ${GITHUB_TOKEN}" \
	     --header "Accept: application/vnd.github.manifold-preview" \
	     --header "Content-Type: application/octet-stream" \
	     --data-binary @$file \
	     "$UPLOAD_URL?name=$BASENAME")

	ARTIFACT_ID=$(echo $ARTIFACT_DATA | ./jq -r '. | .id')
	ARTIFACT_URL=$(echo $ARTIFACT_DATA | ./jq -r '. | .browser_download_url')
	if [ "x$ARTIFACT_ID" = "x" ] || [ "$ARTIFACT_ID" = "null" ]
	then
		echo "Error: Failed to upload artifact."
		echo "Returned data was: $ARTIFACT_DATA"
		exit 1
	fi
	echo "   -- Success (id: $ARTIFACT_ID, url: $ARTIFACT_URL)"
done

# All done.
